[project]
name = 'Decentralized-Existential-Risk-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.civilization-extinction-prevention]
path = 'contracts/civilization-extinction-prevention.clar'
clarity_version = 2
epoch = 2.5

[contracts.cosmic-disaster-early-warning_]
path = 'contracts/cosmic-disaster-early-warning_.clar'
clarity_version = 2
epoch = 2.5

[contracts.existential-threat-response]
path = 'contracts/existential-threat-response.clar'
clarity_version = 2
epoch = 2.5

[contracts.species-backup-coordination]
path = 'contracts/species-backup-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
